#!/bin/bash

########################
# Clear the Algolia rows from the options table related to indexing for debugging purposes.
########################

#######################
# SETUP
#######################
# MySQL Variables
# Should match db.php
mysqlUser='dealerinspire'
mysqlPassword='awesome1234'
mysqlDBName='dealerinspire_wordpress'
mysqlPort='3306'
mysqlHost='127.0.0.1'

# Vagrant Variables
vagrantDirectory='/Volumes/Code/dealerinspire/vagrant/com.dealerinspire.wordpress'
vagrantKey="$vagrantDirectory/.vagrant/machines/default/virtualbox/private_key"
#######################
# END SETUP
#######################
 
# Grab the WPDB Prefix
prefix=$(/usr/bin/ssh vagrant@127.0.0.1 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $vagrantKey -p 2401 "echo \"SELECT REPLACE(TABLE_NAME, 'options', '') AS prefix FROM information_schema.TABLES WHERE TABLE_NAME LIKE 'wp%_options%' LIMIT 1\" | mysql -u $mysqlUser -p$mysqlPassword information_schema -h $mysqlHost -P $mysqlPort | sed -n 2p")
options="options"

/usr/bin/ssh vagrant@127.0.0.1 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $vagrantKey -p 2401 "mysql -u $mysqlUser -p$mysqlPassword $mysqlDBName -h $mysqlHost -P $mysqlPort -D $mysqlDBName -e \
    \"DELETE FROM $prefix$options WHERE option_name LIKE '%%algolia_%%'"
